# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e87a7008feb13adf5a5d3a1ce61a34ef962e89295cef95aa93d279f4e5dbc911d6be061c60a58bf7c2826597ffdeef25a6a631935f6b2464283c7d876275d6e8

test:
  secret_key_base: b47f60c210ee5e23880e8367854d75ef9edc170687f34b02ab9d47f1679f5bfa2d0cdbe2b55f76311c039281ee4ab0bf5d95858f859b27d239ac9b7886bad165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
