# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly

development:
  secret_key_base: b78904ae60cb5c50a8cfa1aa6f9e7da1b0f875cc5b5bbb5855660dd7dc28996bf9660eaa439d573f20c5895273450d0d4a683ec904904743d366216100dff660

test:
  secret_key_base: 89ece93a7db1f37d91d4bc9d2e4c61fe6d80ecf04cc9a30481a3a09f6ff80540c7c24d31a77e4c3b43ef36bd7f088a066e72bee9063a7e74d6f2405e991fa740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
